name: Push to main branch & PR

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install the required toolchain
        run: rustup install

      - name: Run clippy
        run: cargo clippy -- -Dwarnings

      - name: Run formatter
        run: cargo fmt --check

      - name: Build
        run: cargo build --release